const blogs = [
  {
    id: 1,
    title: "Getting Started with JavaScript",
    author: "John Doe",
    category: "Programming",
    excerpt: "Learn the basics of JavaScript and how to use it.",
    content:
      "JavaScript is a powerful language used to build interactive websites...",
    date: "2025-01-01",
    tags: ["javascript", "web", "programming"],
    image: "https://picsum.photos/seed/1/600/400",
  },
  {
    id: 2,
    title: "Understanding CSS Flexbox",
    author: "Jane Smith",
    category: "Design",
    excerpt: "Flexbox makes layout easier in CSS.",
    content:
      "Flexbox is a layout module that allows items to align and distribute space...",
    date: "2025-01-02",
    tags: ["css", "flexbox", "design"],
    image: "https://picsum.photos/seed/2/600/400",
  },
  {
    id: 3,
    title: "Top 10 HTML Tips",
    author: "Alex Brown",
    category: "Web Development",
    excerpt: "Improve your HTML skills with these tips.",
    content:
      "HTML is the backbone of every website. Using semantic tags improves SEO...",
    date: "2025-01-03",
    tags: ["html", "web", "tips"],
    image: "https://picsum.photos/seed/3/600/400",
  },
  {
    id: 4,
    title: "Introduction to React",
    author: "Emily White",
    category: "Frontend",
    excerpt: "React helps you build UI faster.",
    content: "React is a JavaScript library for building user interfaces...",
    date: "2025-01-04",
    tags: ["react", "frontend", "javascript"],
    image: "https://picsum.photos/seed/4/600/400",
  },
  {
    id: 5,
    title: "Why Learn Node.js",
    author: "Michael Lee",
    category: "Backend",
    excerpt: "Node.js allows JavaScript on the server.",
    content:
      "Node.js is built on Chrome’s V8 engine and allows you to build fast servers...",
    date: "2025-01-05",
    tags: ["nodejs", "backend", "javascript"],
    image: "https://picsum.photos/seed/5/600/400",
  },

  {
    id: 6,
    title: "Working with APIs",
    author: "Sarah Green",
    category: "Web Development",
    excerpt: "APIs let apps talk to each other.",
    content:
      "An API is an interface that allows two applications to communicate...",
    date: "2025-01-06",
    tags: ["api", "web", "backend"],
    image: "https://picsum.photos/seed/6/600/400",
  },
  {
    id: 7,
    title: "MongoDB Basics",
    author: "David Black",
    category: "Database",
    excerpt: "MongoDB is a NoSQL database.",
    content: "MongoDB stores data in flexible JSON-like documents...",
    date: "2025-01-07",
    tags: ["mongodb", "database", "nosql"],
    image: "https://picsum.photos/seed/7/600/400",
  },
  {
    id: 8,
    title: "Using Git for Version Control",
    author: "Laura King",
    category: "Tools",
    excerpt: "Git helps track changes in code.",
    content:
      "Git is a distributed version control system used by developers...",
    date: "2025-01-08",
    tags: ["git", "tools", "version-control"],
    image: "https://picsum.photos/seed/8/600/400",
  },
  {
    id: 9,
    title: "Deploying Your First App",
    author: "Chris Adams",
    category: "DevOps",
    excerpt: "Learn how to deploy your web app.",
    content: "Deployment is the process of making your app available online...",
    date: "2025-01-09",
    tags: ["deployment", "devops", "hosting"],
    image: "https://picsum.photos/seed/9/600/400",
  },
  {
    id: 10,
    title: "Web Security Basics",
    author: "Nina Carter",
    category: "Security",
    excerpt: "Protect your web applications.",
    content: "Web security involves protecting websites from attacks...",
    date: "2025-01-10",
    tags: ["security", "web", "hacking"],
    image: "https://picsum.photos/seed/10/600/400",
  },

  {
    id: 11,
    title: "Introduction to Python",
    author: "John Doe",
    category: "Programming",
    excerpt: "Python is simple and powerful.",
    content: "Python is widely used in data science and web development...",
    date: "2025-01-11",
    tags: ["python", "programming"],
    image: "https://picsum.photos/seed/11/600/400",
  },
  {
    id: 12,
    title: "Django for Beginners",
    author: "Jane Smith",
    category: "Backend",
    excerpt: "Build apps faster with Django.",
    content: "Django is a high-level Python web framework...",
    date: "2025-01-12",
    tags: ["django", "python", "backend"],
    image: "https://picsum.photos/seed/12/600/400",
  },
  {
    id: 13,
    title: "Understanding REST APIs",
    author: "Alex Brown",
    category: "Web Development",
    excerpt: "REST APIs are everywhere.",
    content: "REST stands for Representational State Transfer...",
    date: "2025-01-13",
    tags: ["rest", "api"],
    image: "https://picsum.photos/seed/13/600/400",
  },
  {
    id: 14,
    title: "Async JavaScript Explained",
    author: "Emily White",
    category: "Programming",
    excerpt: "Handle async operations in JS.",
    content: "Async JavaScript uses callbacks, promises, and async/await...",
    date: "2025-01-14",
    tags: ["javascript", "async"],
    image: "https://picsum.photos/seed/14/600/400",
  },
  {
    id: 15,
    title: "Intro to TypeScript",
    author: "Michael Lee",
    category: "Frontend",
    excerpt: "TypeScript adds types to JavaScript.",
    content: "TypeScript helps catch errors early by using static typing...",
    date: "2025-01-15",
    tags: ["typescript", "javascript"],
    image: "https://picsum.photos/seed/15/600/400",
  },

  {
    id: 16,
    title: "GraphQL vs REST",
    author: "Sarah Green",
    category: "Web Development",
    excerpt: "Compare GraphQL and REST.",
    content: "GraphQL allows clients to request exactly the data they need...",
    date: "2025-01-16",
    tags: ["graphql", "api"],
    image: "https://picsum.photos/seed/16/600/400",
  },
  {
    id: 17,
    title: "CSS Grid Layout",
    author: "David Black",
    category: "Design",
    excerpt: "Build complex layouts easily.",
    content: "CSS Grid is a two-dimensional layout system...",
    date: "2025-01-17",
    tags: ["css", "grid"],
    image: "https://picsum.photos/seed/17/600/400",
  },
  {
    id: 18,
    title: "Intro to Docker",
    author: "Laura King",
    category: "DevOps",
    excerpt: "Containerize your apps.",
    content: "Docker packages apps with their dependencies...",
    date: "2025-01-18",
    tags: ["docker", "devops"],
    image: "https://picsum.photos/seed/18/600/400",
  },
  {
    id: 19,
    title: "Cloud Computing Basics",
    author: "Chris Adams",
    category: "Cloud",
    excerpt: "Understand the cloud.",
    content:
      "Cloud computing provides servers and storage over the internet...",
    date: "2025-01-19",
    tags: ["cloud", "aws"],
    image: "https://picsum.photos/seed/19/600/400",
  },
  {
    id: 20,
    title: "SEO for Developers",
    author: "Nina Carter",
    category: "Marketing",
    excerpt: "Make your site search-engine friendly.",
    content: "SEO involves optimizing your site for search engines...",
    date: "2025-01-20",
    tags: ["seo", "marketing"],
    image: "https://picsum.photos/seed/20/600/400",
  },

  {
    id: 21,
    title: "Machine Learning Basics",
    author: "John Doe",
    category: "AI",
    excerpt: "Intro to machine learning.",
    content: "Machine learning allows systems to learn from data...",
    date: "2025-01-21",
    tags: ["ml", "ai"],
    image: "https://picsum.photos/seed/21/600/400",
  },
  {
    id: 22,
    title: "Data Science with Python",
    author: "Jane Smith",
    category: "Data",
    excerpt: "Analyze data using Python.",
    content: "Python libraries like pandas and numpy help analyze data...",
    date: "2025-01-22",
    tags: ["data", "python"],
    image: "https://picsum.photos/seed/22/600/400",
  },
  {
    id: 23,
    title: "UI/UX Design Principles",
    author: "Alex Brown",
    category: "Design",
    excerpt: "Design better user experiences.",
    content: "Good UI/UX focuses on usability and clarity...",
    date: "2025-01-23",
    tags: ["ui", "ux"],
    image: "https://picsum.photos/seed/23/600/400",
  },
  {
    id: 24,
    title: "Building Mobile Apps",
    author: "Emily White",
    category: "Mobile",
    excerpt: "Create apps for smartphones.",
    content: "Mobile apps can be built using Flutter or React Native...",
    date: "2025-01-24",
    tags: ["mobile", "apps"],
    image: "https://picsum.photos/seed/24/600/400",
  },
  {
    id: 25,
    title: "Intro to Flutter",
    author: "Michael Lee",
    category: "Mobile",
    excerpt: "Build cross-platform apps.",
    content:
      "Flutter allows building Android and iOS apps from one codebase...",
    date: "2025-01-25",
    tags: ["flutter", "mobile"],
    image: "https://picsum.photos/seed/25/600/400",
  },

  {
    id: 26,
    title: "Web Performance Optimization",
    author: "Sarah Green",
    category: "Web Development",
    excerpt: "Make your site faster.",
    content: "Optimizing images and code improves performance...",
    date: "2025-01-26",
    tags: ["performance", "web"],
    image: "https://picsum.photos/seed/26/600/400",
  },
  {
    id: 27,
    title: "Understanding OAuth",
    author: "David Black",
    category: "Security",
    excerpt: "Secure authentication methods.",
    content: "OAuth allows users to log in using third-party providers...",
    date: "2025-01-27",
    tags: ["oauth", "security"],
    image: "https://picsum.photos/seed/27/600/400",
  },
  {
    id: 28,
    title: "Progressive Web Apps",
    author: "Laura King",
    category: "Web Development",
    excerpt: "Apps that work offline.",
    content: "PWAs combine web and mobile app features...",
    date: "2025-01-28",
    tags: ["pwa", "web"],
    image: "https://picsum.photos/seed/28/600/400",
  },
  {
    id: 29,
    title: "Intro to Blockchain",
    author: "Chris Adams",
    category: "Blockchain",
    excerpt: "Learn how blockchain works.",
    content: "Blockchain is a distributed ledger technology...",
    date: "2025-01-29",
    tags: ["blockchain", "crypto"],
    image: "https://picsum.photos/seed/29/600/400",
  },
  {
    id: 30,
    title: "Smart Contracts Explained",
    author: "Nina Carter",
    category: "Blockchain",
    excerpt: "Automated contracts on blockchain.",
    content: "Smart contracts run automatically when conditions are met...",
    date: "2025-01-30",
    tags: ["smart-contracts", "blockchain"],
    image: "https://picsum.photos/seed/30/600/400",
  },

  {
    id: 31,
    title: "Cybersecurity Careers",
    author: "John Doe",
    category: "Security",
    excerpt: "Explore cybersecurity jobs.",
    content: "Cybersecurity professionals protect systems and networks...",
    date: "2025-02-01",
    tags: ["cybersecurity", "career"],
    image: "https://picsum.photos/seed/31/600/400",
  },
  {
    id: 32,
    title: "Tech Trends 2025",
    author: "Jane Smith",
    category: "Technology",
    excerpt: "What’s next in tech?",
    content: "AI, blockchain, and IoT are shaping the future...",
    date: "2025-02-02",
    tags: ["trends", "tech"],
    image: "https://picsum.photos/seed/32/600/400",
  },
  {
    id: 33,
    title: "Remote Work Tools",
    author: "Alex Brown",
    category: "Productivity",
    excerpt: "Best tools for remote work.",
    content: "Tools like Zoom and Slack help remote teams collaborate...",
    date: "2025-02-03",
    tags: ["remote", "tools"],
    image: "https://picsum.photos/seed/33/600/400",
  },
  {
    id: 34,
    title: "Agile Development",
    author: "Emily White",
    category: "Project Management",
    excerpt: "Build software iteratively.",
    content: "Agile focuses on continuous delivery and feedback...",
    date: "2025-02-04",
    tags: ["agile", "scrum"],
    image: "https://picsum.photos/seed/34/600/400",
  },
  {
    id: 35,
    title: "Intro to Scrum",
    author: "Michael Lee",
    category: "Project Management",
    excerpt: "Framework for agile teams.",
    content: "Scrum divides work into sprints...",
    date: "2025-02-05",
    tags: ["scrum", "agile"],
    image: "https://picsum.photos/seed/35/600/400",
  },

  {
    id: 36,
    title: "Dev Career Roadmap",
    author: "Sarah Green",
    category: "Career",
    excerpt: "Plan your dev journey.",
    content: "A roadmap helps developers focus on key skills...",
    date: "2025-02-06",
    tags: ["career", "developer"],
    image: "https://picsum.photos/seed/36/600/400",
  },
  {
    id: 37,
    title: "Open Source Contribution",
    author: "David Black",
    category: "Community",
    excerpt: "How to contribute to OSS.",
    content: "Open source projects welcome contributions...",
    date: "2025-02-07",
    tags: ["opensource", "community"],
    image: "https://picsum.photos/seed/37/600/400",
  },
  {
    id: 38,
    title: "Intro to Linux",
    author: "Laura King",
    category: "Operating Systems",
    excerpt: "Learn Linux basics.",
    content: "Linux is a popular open-source OS...",
    date: "2025-02-08",
    tags: ["linux", "os"],
    image: "https://picsum.photos/seed/38/600/400",
  },
  {
    id: 39,
    title: "Command Line Tips",
    author: "Chris Adams",
    category: "Tools",
    excerpt: "Be productive with CLI.",
    content: "The command line allows powerful system control...",
    date: "2025-02-09",
    tags: ["cli", "tools"],
    image: "https://picsum.photos/seed/39/600/400",
  },
  {
    id: 40,
    title: "Understanding HTTP",
    author: "Nina Carter",
    category: "Web Development",
    excerpt: "How the web works.",
    content: "HTTP is the protocol used for communication on the web...",
    date: "2025-02-10",
    tags: ["http", "web"],
    image: "https://picsum.photos/seed/40/600/400",
  },

  {
    id: 41,
    title: "Microservices Architecture",
    author: "John Doe",
    category: "Backend",
    excerpt: "Design scalable systems.",
    content: "Microservices break apps into smaller services...",
    date: "2025-02-11",
    tags: ["microservices", "backend"],
    image: "https://picsum.photos/seed/41/600/400",
  },
  {
    id: 42,
    title: "Event-Driven Systems",
    author: "Jane Smith",
    category: "Architecture",
    excerpt: "React to events in real time.",
    content: "Event-driven systems respond to triggers...",
    date: "2025-02-12",
    tags: ["events", "architecture"],
    image: "https://picsum.photos/seed/42/600/400",
  },
  {
    id: 43,
    title: "Serverless Computing",
    author: "Alex Brown",
    category: "Cloud",
    excerpt: "Run code without servers.",
    content: "Serverless lets developers focus on code...",
    date: "2025-02-13",
    tags: ["serverless", "cloud"],
    image: "https://picsum.photos/seed/43/600/400",
  },
  {
    id: 44,
    title: "Monitoring Applications",
    author: "Emily White",
    category: "DevOps",
    excerpt: "Track app performance.",
    content: "Monitoring helps detect errors and bottlenecks...",
    date: "2025-02-14",
    tags: ["monitoring", "devops"],
    image: "https://picsum.photos/seed/44/600/400",
  },
  {
    id: 45,
    title: "Logging Best Practices",
    author: "Michael Lee",
    category: "DevOps",
    excerpt: "Write useful logs.",
    content: "Logs help debug and analyze systems...",
    date: "2025-02-15",
    tags: ["logging", "devops"],
    image: "https://picsum.photos/seed/45/600/400",
  },

  {
    id: 46,
    title: "Introduction to IoT",
    author: "Sarah Green",
    category: "IoT",
    excerpt: "Connect devices to the internet.",
    content: "IoT allows devices to share data online...",
    date: "2025-02-16",
    tags: ["iot", "devices"],
    image: "https://picsum.photos/seed/46/600/400",
  },
  {
    id: 47,
    title: "Robotics Basics",
    author: "David Black",
    category: "Robotics",
    excerpt: "Learn how robots work.",
    content: "Robotics combines hardware and software...",
    date: "2025-02-17",
    tags: ["robotics", "engineering"],
    image: "https://picsum.photos/seed/47/600/400",
  },
  {
    id: 48,
    title: "Game Development Intro",
    author: "Laura King",
    category: "Game Dev",
    excerpt: "Create your first game.",
    content: "Game development involves graphics, logic, and physics...",
    date: "2025-02-18",
    tags: ["games", "development"],
    image: "https://picsum.photos/seed/48/600/400",
  },
  {
    id: 49,
    title: "AR and VR Explained",
    author: "Chris Adams",
    category: "XR",
    excerpt: "Virtual and augmented reality.",
    content: "AR overlays digital content while VR creates virtual worlds...",
    date: "2025-02-19",
    tags: ["ar", "vr"],
    image: "https://picsum.photos/seed/49/600/400",
  },
  {
    id: 50,
    title: "Future of Artificial Intelligence",
    author: "Nina Carter",
    category: "AI",
    excerpt: "What lies ahead for AI?",
    content: "AI will continue to shape healthcare, finance, and education...",
    date: "2025-02-20",
    tags: ["ai", "future"],
    image: "https://picsum.photos/seed/50/600/400",
  },
];
